from sell import sell
from buy import buy
def sell_invoice():
    user_purchased_laptops,today_date_and_time,grand_total,total,name,phone_number,shipping_cost=sell()
    with open(str(name)+str(phone_number)+".txt","w") as file:
         
         file.write("\t\t\t\tZEXTER INTERNATIONAL")
         file.write("\n")
         file.write("\t\tKamalpokhari, Kathmandu | Phone No: 9843050505 ")
         file.write("\n")
         file.write("\t\t\t\t\tLaptop Shop Bill")
         file.write("\n")
         file.write("\n")
         file.write("Name of the Customer: " + str(name))
         file.write("\n")
         file.write("Contact number: " + str(phone_number))
         file.write("\n")
         file.write("Date and time of purchase: " + str(today_date_and_time))
         file.write("\n")
         file.write("------------------------------------------------------------")
         file.write("\n")
         file.write("Purchase Detail are:")
         file.write("\n")
         file.write("------------------------------------------------------------")
         file.write("\n")
         file.write("Item Name\t\tQuantity\t\tUnit Price\t\tTotal")
         file.write("\n")
         file.write("------------------------------------------------------------")
         file.write("\n")
         for i in user_purchased_laptops:
             file.write(str(i[0])+"\t\t\t"+str(i[1])+"\t\t\t"+str(i[2])+"\t\t\t"+str(i[3])+"\n")
         file.write("------------------------------------------------------------")
         file.write("\n")
         file.write("Sub Total:$"+str(total))
         file.write("\n")
         file.write("Shipping Cost:$"+str(shipping_cost))
         file.write("\n")
         file.write("Grand Total:$"+str(grand_total))


def buy_invoice():
     name, user_purchased_laptops, phone_number, grand_total, VAT,today_date_and_time,total = buy()
     with open(str(name)+str(phone_number)+".txt","w") as file:     
         file.write("\t\t\t\tZEXTER INTERNATIONAL")
         file.write("\n")
         file.write("\t\tKamalpokhari, Kathmandu | Phone No: 9843050505 ")
         file.write("\n")
         file.write("\t\t\t\t\tLaptop Shop Bill")
         file.write("\n")
         file.write("\n")
         file.write("Name of the Manufacturer: " + str(name))
         file.write("\n")
         file.write("Contact number of the Manufacturer: " + str(phone_number))
         file.write("\n")
         file.write("Date and time of purchase: " + str(today_date_and_time))
         file.write("\n")
         file.write("------------------------------------------------------------")
         file.write("\n")
         file.write("Purchase Detail are:")
         file.write("\n")
         file.write("------------------------------------------------------------")
         file.write("\n")
         file.write("Item Name\t\tQuantity\t\tUnit Price\t\tTotal")
         file.write("\n")
         file.write("------------------------------------------------------------")
         file.write("\n")
         for i in user_purchased_laptops:
             file.write(str(i[0])+"\t\t\t"+str(i[1])+"\t\t\t"+str(i[2])+"\t\t\t"+str(i[3])+"\n")
         file.write("------------------------------------------------------------")
         file.write("\n")
         file.write("Sub Total:$"+str(total))
         file.write("\n")
         file.write("Grand Total:$"+str(grand_total))
